cluster-cancel: "scancel"
restart-times: 3
jobscript: "slurm-jobscript.sh"
cluster: "slurm-submit.py"
cluster-status: "slurm-status.py"
max-jobs-per-second: 10
max-status-checks-per-second: 10
local-cores: 1
latency-wait: 120
use-conda: False
use-singularity: True
jobs: 20
printshellcmds: True
